### ISSUE TITLE
Key error - Jirina

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/Genie#10]
`mesh_gen3.py`:

```
       for j in range(len(face_edges[i])):
            for e in face_edges[i][j]:
                try:
                    bw_edges[e].attach_to_plane(surf, vertices_tr[e[0]][0:3:2], vertices_tr[e[1]][0:3:2])
                except KeyError:
                    bw_edges[(e[1], e[0])].attach_to_plane(surf, vertices_tr[e[1]][0:3:2], vertices_tr[e[0]][0:3:2])

```

Navim jak to ma fungovat, ale pada to obcas i v ramci osetreni vyjimky, asi se nenajde bod ve `vertices_tr`.
takze to je treba teke osetrit a amyslet se proc se to asi deje.

**Comment by kralovcova** [comment]
Do sdíleného adresáře GeoStab3 jsem nahrála jednu z úloh, při které se chyba vyskytla. Je to v poadresáři [2020-11-09_KeyError_Jirina](https://drive.google.com/drive/folders/107VDDrccM5rL-1wwMo-9Ag4Wy1_6Rb5V?usp=sharing)
j.k.

**Comment by radeksrb** [comment]
Chyba opravena.

Nicméně při spuštění úlohy "2020-11-09_KeyError_Jirina" nastane jiná chyba:
"RuntimeError: There is a requested electrode that does not match the given mesh."
Pro snap distance 0.4 nedojde k pritazeni vsech elektrod k chodbe, pro 1.0 ano.
Tento problém je aktuálně v řešení, elektrody které nebudou uvnitř inverzní meshe, budou vyřazeny z inverze.
