### ISSUE TITLE
Inversion dialog

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/Genie#12]
-   labely udelat citelnejsi s mezerami, nemusi doslova odpovidat vnitrnim promennym
-   Nastaveni meshe potrebuje vysvetleni v dokumentaci, revizi co vsechno ponechat a pripadne tooltipy.
-   verbose ponechat jak je, zrusit sekci Test options
-   k_ones ... jeste potreba? 
- log option ponechat, dat na konce nastaveni  Inversion
-  optimizeLambda vybrat automaticky

**Comment by radeksrb** [comment]
Hotovo.
