### ISSUE TITLE
constrained resistivity model

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/Genie#14]
Potrebujeme uvazovat model:

m=ln((a-r)/(b-3))

Kde m je parametr ktery se optimalizuje, r je rezistivita. 

Takze kdyz vyjadrim tu rezistivitu:

r = (a + b*exp(m))/(1+exp(m))

To urcite jde udelat, ale jeste jsem to v Pygimli nenasel.

... to bo continued.

**Comment by radeksrb** [comment]
Vyreseno v 3a9cff7.
