### ISSUE TITLE
pg.geometricFactors() počítá geometrický faktor pro nás nevhodně

### ISSUE THREAD

**Issue by radeksrb** [GeoMop/Genie#22]
Funkce https://github.com/gimli-org/gimli/blob/master/core/src/bert/bertMisc.cpp#L131 počíta geometrický faktor medou "3D mirrorspace", pro naše účely by byla lepší medota "3D fullspace".

Navrhované řešeni:
Vytvořit vlastní funkci, která bude počítat tak jak chceme.

Touto chybou mohou být dotčeny výpočty 10A, 10B, 11A, 22A, 24A.

**Comment by jbrezmorf** [comment]
Jaká je motivace toto řešit?

Full space a mirror space by se měl lišit přenásobením 0.5. Jelikož by k tomu došlo pro všechna měření nemělo by to mít na inverzi vliv. Takže pokud tu není nějaká indicie toho, že by to vliv mít mělo, tak bych to neřešil.

**Comment by radeksrb** [comment]
Ve výsledku se požije vzorec https://github.com/gimli-org/gimli/blob/master/core/src/bert/bertMisc.cpp#L214 ovšem my pořebujeme https://github.com/gimli-org/gimli/blob/master/core/src/bert/bertMisc.cpp#L202 , který se nepožije protože funkce exactDCSolution je vždy volána s parametrem surfaceZ=0.0. Dle vzorců je patrné že nejde pouze o dvojnásobnou hodnotu, ale výsledek u "mirror space" není invariantní vůči posunutí ani natočení.

**Comment by jbrezmorf** [comment]
Jasný. Zdá se tedy, že exactDCSolution má podporu pro full 3D, ale 'geometricFactors' to nepoužívá. Bude tedy lépe si 'k' počítat sami podle potenciálu: '1.0 / (4.0 * PI * r)' umístěného v jednotlivých elektrodách.

**Comment by radeksrb** [comment]
Hotovo.
