### ISSUE TITLE
Velké elementy v blízkosti vrtů

### ISSUE THREAD

**Issue by radeksrb** [GeoMop/Genie#23]
Velikost elementů sítě v blízkosti chodeb je definována parametrem "Edge length" v dialogu "Run inversion". Velikost elementů se se vzdáleností od chodby zvětšuje. Velikost elementů v blízkosti vrtů není řešena. To způsobuje, že inverzní úloha je špatně definovaná.

Navrhované řešení:
V blízkosti vrtů omezit velikost elementů, tak jako tomu je v blízkosti chodby.

**Comment by jbrezmorf** [comment]
Řešení:
- GMSH předepsat všechny body elektrod (zprojektované) a na nich předepsat jemnější meshstep.

**Comment by radeksrb** [comment]
Hotovo.
