### ISSUE TITLE
gmsh 4.8.0

### ISSUE THREAD

**Issue by radeksrb** [GeoMop/Genie#24]
V případě použití gmsh verze 4.8.0 v knihovně bgem nastane chyba:
Exception: OpenCASCADE curve is null in projection
ve funkci:
mesh_from_brep
https://github.com/GeoMop/Genie/blob/master/src/genie/invert.py#L599
Pravděpodobně způsobeno tím, že nějaká projektovaná úsečka je příliš krátká.
Při použití verze 4.7.1 k problému nedochází.

**Comment by jbrezmorf** [comment]
4.8 reports errors as Python exceptions.

**Comment by jbrezmorf** [comment]
Check that the same message is present in version 4.7 but not thrown as an exception.
Catch OpenCASCADE exceptions and covert them to warnings as long as the mesh file is created.

**Comment by radeksrb** [comment]
Je to řešeno pomocí vyjímky již ve verzi 4.7.1 viz:
https://gitlab.onelab.info/gmsh/gmsh/-/blob/gmsh_4_7_1/api/gmsh.py#L1382

Odchytit vyjímku nepomuže, výsledek není v pořádku.

**Comment by jbrezmorf** [comment]
Po prozkoumání zdrojáků GMSH to vypadá, že v modelu je nějaká Edge (= topologická hrana) bez přiřazené křivky. To asi dříve nevadilo, a teď to vadí.
V brep_writer.py je ovsem v Edge._childs osetreno pridani implicitni krivky, ale cely ten vypis je dost komplikovany. Asi by bylo dobre dat si nejaky assert nebo kontrolni vypis do Edge._subrecordoutput:
- ze self.repr je neprazdne
- ze uspeje jeden z tech ifu

**Comment by radeksrb** [comment]
Vyřešeno v bgem https://github.com/GeoMop/bgem/commit/4428b2286b5d1711b3c2fcd9f3651a004d91704f.
