### ISSUE TITLE
Bokorys v panelu mapy

### ISSUE THREAD

**Issue by radeksrb** [GeoMop/Genie#27]
Potrebujeme pridat i bokorys, pro vizualizaci vertikalniho rozsahu.

**Comment by jbrezmorf** [comment]
1. funkce na adaptivní decimaci založená na tvorbě pomocné sítě. Parametr krok výsledné sítě bodů. Krok pomocného gridu volen automaticky, aby počet elementů ve směrech byla mocnina dvou.
2. Do připravy projektu, možnost provedení první decimace cca 20cm pomocná síť.
3. Druhá decimace na třetinový krok získáme mračno bodů pro vizualizaci ve scéně.
4. Volba roviny řezu pomocí přímky v půdorysu.
5. Nové okno s řezem, projekce bodů.
6. Intenzita bodu podle vzdálenosti od roviny řezu.

**Comment by jbrezmorf** [comment]
Hotovo. Šeď bodu dle vzálenosti pouze ve dvou intenzit šedi.

Zkusit též zobrazovat body s průhledností spojitě dle logaritmu vzdálenosti od roviny řezu.
