### ISSUE TITLE
Testovani 5.11.

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/Genie#3]
1. Okna pro import (souradnice, mracno bodu) maji samostatne tlacitko READ, to je zbytecne, nacteni by melo probehnout primo po vyberu souboru.
1.  pri nacitani mracna bodu je potreba toto udelat v samostatnem vlakne, protoze jinak se to nedostane do hlevni aplikace a neni napr. mozno zvetsit okno nebo rolovat ve vypisu.
1.  vypada to, ze se pouze souradnice kopiruji do jineho suboru `point_cloud.xyz.tmp` a jeste to nemozne dlouho trva (asi 3 minuty).
1.  jak se provede vytvoreni geometrie z bodu na povrchu?
1.  umoznit tahani mapy i mimo jeji rozsah, pri zoomu na okraj nelze okraj pretahnout doprostred obrazovky
1.  jak velka je vypocetni a jak velka invertovana oblast vuci vyberu cervenym obdelnikem
  (asi margin, upravovat relativne vuci obdelniku)
1.  nepovolit zkoseni, pomoci jednoho kolecek pouze otacet a roztahovat
1.  potrebujeme pridat i bokorys, pro vizualizaci vertikalniho rozsahu 
1.  potreba zobrazit k jakym elektrodam ktere soubory patri, tj. vyznacit pouze vybrane soubory
1.  tool tipy k tlacitkum vedle vyberu oblasti
1.  run inversion (bez analyze measurement) nic neprovede, potreba nejak reportovat aspon ve status baru 
  ... teprve v konzoli objeven problem:
  ```
Traceback (most recent call last):
  File "/home/jb/workspace/Genie/src/genie/ui/tabs/inversion_preparation.py", line 631, in _handle_run_invButton
    from ..dialogs.run_inv import RunInvDlg
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/run_inv.py", line 5, in <module>
    from genie.core import ert_prepare, st_prepare
  File "/home/jb/workspace/Genie/src/genie/core/ert_prepare.py", line 3, in <module>
    import pygimli as pg
ModuleNotFoundError: No module named 'pygimli'
```
Zaver, odchycene vyjimky reportovat.
1.  pygimli nejde nainstalovat pres PIP, popsat instalaci na hlavni git strance
1.  chybi explicitni ulozeni, muze byt ok pokud to automaticke bude chytre a provede caste ukladani a zejmen pri padu aplikace

1.  hlasi chybu 'Select measurement first.' i pri vybranem mereni
![Screenshot-20201105125910-267x140](https://user-images.githubusercontent.com/326204/98238560-d411e580-1f66-11eb-8600-d0cef574ec30.png)

1.  nejasna verze pygimli, analyse_measurements error:
```
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/analyse_measurement_dialog.py", line 92, in _analyse
    k = pg.geometricFactors(data)
AttributeError: module 'pygimli' has no attribute 'geometricFactors'
```

**Comment by jbrezmorf** [comment]
Used version of pygimli is 1.0.12.

**Comment by jbrezmorf** [comment]
Vyresit co jde snadno, pro zbytek udelat issues.

**Comment by radeksrb** [comment]
Hotovo.
