### ISSUE TITLE
Testing 27.11. Genie ERT

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/Genie#41]
- [x] Creating new project leads directly to 'XLSReader' dialog. Rename the dialog to explain what kind of data the XLS file contains. Proposed title: 'Open measurement metadata file'. Review also titles of other dialogs.

- [x] Soubor souřadnic v tests/BukovERT obsahuje chyby. Pokusit se opravit, smazat z něj nepotřebné taby.
- [x] Výpis chyb při načítání XLS indikovat že vstup obsauje chyby. Reportovat zda jsou použita pouze měření bez chyb. 
    - Přidat po okno červený text "Document contains errors. Some measurements omitted."
    - Závěrečný výpis bezchybných měření, upravit titulek: "Loading measurements without errors:"
    - ve výpisech chybných řádků upravit formát chybových zpráv CO, KDE, např. ERROR: Missing value 'X'. row 1455, col H
- [x] Zobrazení řezu:
   - zvýraznit oddělující čáru oken
   - zobrazení řezu jako pohledu není intuitivní, zobrazit body na obě strany od roviny řezu intenzita v závislosti na vzdálenosti, škálovat vzdálenost podle velikosti normály ovládacího prvku
   - Experimentálně: polohu řezu fixovat na střed půdorysu
- [x] Maximalizovat okno při startu, zmenšit ovládací prvky, použít ikony pro znázornění funkcí ovládacích prvků, viz. #38
- [x]  rozšířená výpočetní oblast by se měla rozšiřovat i ve vertikálním směru
- [x] Chybová zpráva při prázdném výběru měření upravit na: "No measurement selected.\n Select one or more in the Measurements panel.
- [x] Přidat to menu pložku View pro zobrazení panelů. Při jejich zavření je není možné zobrazit.
-  [x] Log inverze ma jiz malo prostoru. Navrhuju zmenit dialog na zalozku a dat nastaveni doleva a log doprava. Všechny zalozky by se presunuly hned na uroven pod halvni menu.
- [x] Reported in #24. Chyba pro ruzna nastaveni oblasti a ruzne verze BGEM. Snad problem s nejakou zmenou v GMSH-SDK:
```
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/../../invert.py", line 660, in mesh_from_brep
    model.make_mesh([compound])
  File "/home/jb/miniconda3/envs/genie1/lib/python3.7/site-packages/bgem/gmsh/gmsh.py", line 637, in make_mesh
    gmsh.model.mesh.generate(dim)
  File "/home/jb/miniconda3/envs/genie1/lib/python3.7/site-packages/gmsh-4.8.4-Linux64-sdk/lib/gmsh.py", line 1523, in generate
    raise Exception(logger.getLastError())
Exception: OpenCASCADE curve is null in projection
```

**Comment by radeksrb** [comment]
Hotovo.
