### ISSUE TITLE
Zobrazeni elektrod, bodu, mereni

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/Genie#5]
- mracno body zobrazit pruhledne, sedive (kvuli viditelnosti mapy)

- vsechny elektrody stejnou barvou (zkusit zelene)
- zvyraznit elektrody zahrnute do inverze (podle vyberu mereni), zkusit cervene

- analyse measurement pres dvojklik do tabulky mereni

**Comment by radeksrb** [comment]
Hotovo.
