### ISSUE TITLE
Testovani 6.11. funkcni meshlab

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/Genie#8]
```
Traceback (most recent call last):
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/../../invert.py", line 732, in <module>
    main()
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/../../invert.py", line 42, in main
    inv_ert(inversion_conf, project_conf)
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/../../invert.py", line 162, in inv_ert
    fop.setMesh(mesh)
RuntimeError: There is a requested electrode that does not match the given mesh. 
```
Elektrody ktere nejdou pritahnout nutno vynechat, reportovat pocet zahozenych elektrod.

**Comment by radeksrb** [comment]
Pokud jsou elektrody ve vrtu, nejdou pritahnout k povrchu chodby, tyto asi chceme nechat.
Takze jde spis o vyrazeni elektrod ktere jsou mimo inverzni mesh.
To lze zaridit, ale az ve chvili kdy je hotova inverzni mesh, pak by bylo nutne je vypreparovat z objektu dat mereni, vcetne tech radku mereni, ktere se na ne odkazuji.
Dava smysl mit inverzni mesh, která nepokryva vstupni elektrody?

**Comment by jbrezmorf** [comment]
Rozumim a souhlasim.
Predstavuju si, ze si vyberu nejakou oblast ktera me zajima a mam ji relativne dobre pokrytou nejakymi merenimi, ale nektera ta mereni zasahuji i mimo tu oblast a tam je treba nemam dost husta.

**Comment by jbrezmorf** [comment]
hotovo.
